APPLICATION = app-qa

BOARD = beduino-pro-mini

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../RIOT

USEMODULE += xtimer

DEVELHELP ?= 1
QUIET ?= 1

include $(RIOTBASE)/Makefile.include
